name = "siat"
version = "0.1.0"
defaultTargets = ["Siat"]

[leanOptions]
pp.unicode.fun = true

[[lean_lib]]
name = "Siat"
srcDir = "."
roots = ["Main_Standalone", "Bedrock", "Invariance", "Main"]

[[require]]
name = "docgen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"