name = "siat"
version = "0.1.0"
defaultTargets = ["Siat"]

[[require]]
name = "mathlib"
git = "https://github.com"

[[lean_lib]]
name = "Siat"
srcDir = "."
roots = ["Main_Standalone", "Bedrock", "Invariance", "Main"]

[[require]]
name = "docgen4"
git = "https://github.com"
rev = "main"
