name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install elan
        run: |
          curl https://githubusercontent.com -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Install Toolchain
        run: |
          elan toolchain install $(cat lean-toolchain)
          elan default $(cat lean-toolchain)

      - name: Get Mathlib cache
        run: lake exe cache get || true

      - name: Build project API documentation
        run: lake -R -Kenv=dev build Siat:docs

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .lake/build/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


