name: Build and Deploy Docs
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install elan
        run: |
          curl https://lean-lang.org -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build documentation
        uses: leanprover-community/docgen-action@v1
        with:
          blueprint: false
