name: Build and Deploy Docs
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This official action installs Lean, Lake, and Elan for you correctly
      - name: Build documentation
        uses: leanprover-community/docgen-action@v1
